language: node_js
node_js:
  - "0.10"
script:
  - echo 'Hello Firebase'
install:
  - npm install -g firebase-tools
  - npm install -g firebase-import
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
  - firebase-import --firebase_url https://hellofirebasemaro.firebaseio.com --json data.json --force
